/**
select 'drop '||object_type||' '||owner||'.'||object_name||' CASCADE CONSTRAINTS;' 
from all_objects 
where owner='DETECTION' 
and object_type in ('TABLE','VIEW');
**/

drop TABLE DETECTION.BINARY_1 CASCADE CONSTRAINTS;
drop TABLE DETECTION.COMPOSITE_REGION CASCADE CONSTRAINTS;
drop TABLE DETECTION.COMPOSITE_REGION_MEMBER CASCADE CONSTRAINTS;
drop TABLE DETECTION.CONTACT CASCADE CONSTRAINTS;
drop TABLE DETECTION.CRAFT CASCADE CONSTRAINTS;
drop TABLE DETECTION.CRAFT_IDENTIFIER_TYPE CASCADE CONSTRAINTS;
drop TABLE DETECTION.CRAFT_TYPE CASCADE CONSTRAINTS;
drop TABLE DETECTION.DETECTED_CRAFT CASCADE CONSTRAINTS;
drop TABLE DETECTION.DETECTION CASCADE CONSTRAINTS;
drop TABLE DETECTION.DETECTION_MESSAGE CASCADE CONSTRAINTS;
drop TABLE DETECTION.DETECTION_RULE CASCADE CONSTRAINTS;
drop TABLE DETECTION.DETECTION_RULE_CRAFT CASCADE CONSTRAINTS;
drop TABLE DETECTION.MESSAGE_RECIPIENT CASCADE CONSTRAINTS;
drop TABLE DETECTION.MESSAGE_TEMPLATE CASCADE CONSTRAINTS;
drop TABLE DETECTION.REGION CASCADE CONSTRAINTS;
drop TABLE DETECTION.REGION_CRAFT CASCADE CONSTRAINTS;
drop TABLE DETECTION.SIMPLE_REGION CASCADE CONSTRAINTS;
drop TABLE DETECTION.SIMPLE_REGION_TYPE CASCADE CONSTRAINTS;
drop TABLE DETECTION.XUML_QUEUED_SIGNAL CASCADE CONSTRAINTS;
